### ISSUE TITLE
Maybe a error in start_modes_and_arguments.md

### ISSUE THREAD

**Issue by muye998** [espressif/esp-debug-adapter#3]
[the link](https://github.com/espressif/esp-debug-adapter/blob/46fd1e08cb808dfb8c3f36daceea5f47d9d5cb9a/docs/start_modes_and_arguments.md#start-modes-and-arguments)
### I can not find the directory cripts
![image](https://user-images.githubusercontent.com/87895422/220517160-cdfc78ad-4c24-4b96-9b23-de0104983646.png)

**Comment by muye998** [comment]
And I am not skillful to the computer systerm. Can you tell me what is the meaning of Variables set ?
BTW, I am developing esp32 in linux base virtual machine, Big thanks!

**Comment by brianignacio5** [comment]
Are you using the debug adapter directly ? How are you starting this adapter ?

You can just follow along the vscode extension tutorials as shown [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/toc.md)

**Comment by muye998** [comment]
No, I don't use the debug adapter directly.
When I was confused by the debug, I fought many ways to solve , and I thought, maybe, this a script to generate a launch.json in my env, I am sorry.



> You can just follow along the vscode extension tutorials as shown [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/toc.md)

thank you!

**Comment by muye998** [comment]
Sloved, thanks!
